feat: download cargo-binstall from github release
Signed-off-by: David Bernard <david.bernard.31@gmail.com>

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,14 +10,23 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+archive_format=""
+case "$OSTYPE" in
+darwin*) archive_format="zip" ;;
+linux*) archive_format="tgz" ;;
+*) fail "Unsupported platform" ;;
+esac
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.${archive_format}"
 
 # Download tar.gz file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
 #  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+case "$archive_format" in
+zip) unzip -j -o -d "${ASDF_DOWNLOAD_PATH}" "$release_file" || fail "Could not extract $release_file" ;;
+tgz) tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file" ;;
+*) fail "Unsupported platform" ;;
+esac
 
 # Remove the tar.gz file since we don't need to keep it
 rm "$release_file"
